# Fuse Core Theme for Jekyll - Settings
# https://github.com/tsjensen/fuse-core

markdown: kramdown
permalink: pretty
exclude: ['README.*', 'LICENSE.txt']
sass:
    style: expanded


# CAUTION
# When modifying this file, take care to preserve the indentation. This is YAML ...

# Main Headline, name required, subtitle optional
name: ISC
#subtitle:
subtitle: Ingeniero Sistemas Computacionales 

# Title attribute of HTML Page, uses 'name' from above if empty
title: Fuse Core

# Information for web crawlers / Google, all of them optional
# 'description' and 'keywords' simply set the corresponding meta tags,
# 'crawl' is the 'Robots' tag http://www.robotstxt.org/meta.html
robots:
    description: One line of text describing the content of the page in less than 140 characters.
    keywords: foo, bar, baz
    crawl: index,follow

# website address when deployed, also given as canonical link
url: https://Roberto1219.io/fuse-core/

# The 'baseurl' is prepended to all website-internal links.
# 'baseurl' will often be '', but for a project page on gh-pages, it needs to be the project name.
# If not empty, be careful to keep the leading slash, and don't add a slash at the end.
#baseurl: ''
baseurl: '/mi-sitio-web'

# Enable Google Analytics. Leave empty (just "ga:" with subitems commented out) to disable.
# In order to comply with EU cookie law, enable 'cookieconsent' to show a little popup asking users to acknowledge the GA cookies.
# Also, some places require you to anonymize the users' IPs, which can be enabled via 'anonymizeip' below. You normally want that.
# https://support.google.com/analytics/answer/2763052
#ga:
ga:
    account: 'UA-120960520-1'
    cookieconsent: true
    anonymizeip: true

# Plausible.io Analytics (alternative to Google Analytics that does not need cookies -> no cookie consent required)
# A config setting is required in plausible to enable tracking of the outbound links. Details described here:
# https://plausible.io/docs/outbound-link-click-tracking
# Leave empty (just "plausible:" with subitems commented out) to disable.
#plausible:
plausible:
    domain: 'tsjensen.github.io'


# A picture of you, square(!), at least 180x180 pixels, more is better. Recommended file size < 100 KB.D"
avatar: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxMSEhMSEhMQFhUVGRoXGBcXFxgVHhcWFRMYGxgVGhYYIioiGBslHRcXIjIiJSktLi4uHiAzODMtNzQtLisBCgoKDg0OGxAQGy0lICU1LS41LTUtLSsvKy8tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLy0tLS0tLS0tLS0tLS0tLf/AABEIAOEA4AMBEQACEQEDEQH/xAAcAAEAAwADAQEAAAAAAAAAAAAABQYHAQMEAgj/xABEEAABAwIDBQQHBAgFBAMAAAABAAIDBBESITEFBkFRYRMicYEHMkJSkaGxFCOCwTNDU2JykqKyFVRz4fA0Y9HSFhdE/8QAGgEBAAMBAQEAAAAAAAAAAAAAAAMEBQIBBv/EADYRAAICAQIEAwUGBgMBAAAAAAABAgMRBDESIUFRE3GBImGRocEFMlKx4fAUIzNCYtEVcpKi/9oADAMBAAIRAxEAPwDDy48ygOMR5lAMR5lAMR5lAMR5lAMR5lAMR5lAMR5lAMR5lAMR5lAMR5lAMR5lAMR5lAMR5lAMR5lAMR5lAMR5lAMR5lAMR5lAMR5lAMR5lAMR5lAMR5lAMR5lAMR5lAMR5lAMR5lAMR5lAcIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgPqNhcQACSdABcnyTYYyTFJunWyZtppvxNwf32uoZaiqO8kSxosltFkjF6PK86xMb4yM/IlRPW09/kyRaS3sJPR5XjSNjvCRv5kItdT3+TH8Jb2+ZH1e6NbHm6mm/CO0/supI6mmW0kcSosjvFkPLEWktcCCNQQQR5FTkTWD4Q8CAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAldh7vVFWbQsJA1ee61vi4/QZqK26FazJkldU7Puotmy91KVjsJ7aulGrIO7E08nykgf1X6KpZqLGs8oru9/gWYUQXL7z923xLA+X7KLPloKBvuRNE0pFuZAufwlV8eJspT8+S/fqT54N2o+XNkNWb00Ojptp1B54zE3+VhZ9FNHT3dFGPpkhlfX1cn64Iybeqgvls4P6ySkn5gqVaa7rZ8jh31fg+Yi3qoL3OzWt6slIPyAR6e7pZ8jzxqvwfMkqTemgv3ZNp055iQyNH4XOd/ao5ae7qoy9MEkbqunEvUmoqkVIwsqKGtb+znYIpPJwGR/AFA14fNxlH3rmibPHs1Lz5Mg9q7rUjjYtmoZToJPvIXE8GygkD4jwU9eosW2Jr3cn8CCdMPfF+/b4lR25u3UUh+9Z3DpI3vMPg7h4GxVyq+Fn3X6dStZVKG6IhSkYQBAEAQBAEAQBAEAQBAEAQBAEByEBddh7pMjDJa0PvJ+ipWfpJT1GrRz0txIVKzUuTcaum76ItV0JYdnXZdWWLbVbFAxorXNa0DuUFObADh2rhbF4ZN6OVauMpvNf8A6f0LE5KKxP8A8r6lO2tvvUSjs4cNPCMhHF3cuRcM/hYdFcr0kI85c33ZVnqJvkuS7IhNn7OmqX4ImPkeczbPXi5xyHiVYnOMFmTwiGMZTeEi/wCxPRjo6rkP+nH9C8j6DzWbb9o9K16svV6LrNkvWbnUg7sNCXn3nTSRtHi7EXHyaQoo6uzeU8eif7+JJLTw2jH54IaX0Yue7F2kUQPsNxy2/E6xU3/IxS2b+RE9E31wQ+2PR1VwgujwzNHuZO/kOvkSpqtdVPk+RFPSWR5rmVFzS0kEEOBzByII+hV3cq7Fi2PvrUwDA8ieI5GOXvZcg45j5joq1mlrnzXJ90Tw1E48nzXvLjsLaUM4IontYSO/Qz96N449mT6vlcc2hU7YSg/5nP8AyW68y1XOMv6f/l7ehCbb3RZNjfRtfHKzOWkfk5v70Z9pvKxIPA8FPXqXHCs5p7S6epFZQpZcN+qKK5pBIIIIyIOViOCvFM4QBAEAQBAEAQBAEAQBAEAQBAaLuvu99l7OR8YkrJReGF2kTf20vugfG9gM9M+67jyk8RW77+5F2qrgw2syey7e9nO8O87aQvjgf21W7KapIBwn9nGNAByGQ6m9vKtO7EnJYj0j9We2XeG2ovMur/0Z5LK55LnEucTckkkkniSdStFLCwii3kum425TatnbzPIjDi3A31nFtr3d7Iz4Z+Co6vWeE+GK5lvT6bxFxPY1TZ9BFAwRwsaxo4NGvUnUnqVj2WSm8yeTThBQWEj0qM7CAIAgIrbO71NVD76JpdweO64fiGZ8DcKerUWVfdZDZTCe6KPtT0XOFzTTA/uyix/nbr8AtCv7Sj/einPQv+1lL2vsaoo5GiZpY71mOBBBsdWubxGXUZK/XbC1ZjzKk65VvEi27v70NqsENW8xzsP3FU3JzXe6/gQeN8jx5qpbp3XmVaynvH/RZru48Kb59Gevefd41Zf3Gx10YxOa3JtTGP1sfX5g5HgVxTeq8c8wf/y+zOrauP3S/PyM1c0gkEEEZEHgeS0igcIAgCAIAgCAIAgCAIAgCAuW4+zGNaa2VokwvEcEQIvJOc2i3ADX4ngqepm3/Ljy7vsizp4L779F3ZKb27cdSNfCx4dWTWNRK32ARlEz3QAbDkM9TcRaepWNSa9lbL6slus8NOK+8939DOVolEkNhTtbMwSNDo3EMkaeLHGxPQjUEaEBcWJ8L4dzuDXEs7G17rbE+xxPhDsTe0c5pOuFwFr9RaywdTd4slL3GvRX4acSZVYnCAIAgCAIAgI3eDY0dXC6GQa5tdxY/g4f8zF1NRdKqXEiK2pWRwzB9pUL4JXwyCz2Gx/IjoRYhfRQkpRUkYsouLwy7bobb+1NZSTPLJ4+9Sz8Q4D9G73gRlbiLjWyo6irw27IrKf3l9S3TZxrgb5rZnn342YJGGsa0Rytf2VVFf1ZOD28w7I9QQea700+F+G+a3T93b0Ob4ZXHs9mveUdXSoEAQBAEAQBAEAQBAEAQEjsPbElLK2WPCS2+ThiGYIvbgbHUKOytWR4ZHddjg+JHiqJ3Pc57yXOcSSTqSTcldpJLCOW23lnWvTwtO5W6L6x3aOJZCw5u4uI9lv5ngqmp1UaVjdliih2PPQ2tYJsET/8mo/81T/ztU38Nb+FkXj1/iRIUtVHK3HG9j2+8xwcPC4UUoSi8SWCSMlJZTO5cnQQHDumq9PGU7eukkZC+aor5mAXwxwgRAu9lgzLneZPE5BaGmnFzUYQ9XzKd8Wo8U5fAjvRLtKST7THI977YHguJcRfEHZnwb8F39owS4WkcaKbeUzQ1lmgZ56WdiYmMq2DNlmSdWk913kTb8Q5LU+zrubrfoZ+tq5caMwjeWkEEgg3BGRBGhB4FaxnEjt3bktW8SS4b4Wt7otfCD3jzOZ+KjqqjWsRJLLJTeWRikIwgCAIAgCAIAgCAIAgJPd2gjnnbHLII2ZkuIys3N1zfu5A587KO2TjFuKyzuuKlLDeDzbSphFK+MOxhhLcVrXtqQOV13F5SZzJYeDyr08PRQUMk7xHExz3nQD6nkOpXMpRisyeEdRi5PCNl3N3dmpY29tO9xANomm0bLm5/jdcnP66rE1WpjY/ZXr1NXT0ygvafp0Jba9dgaWNZLJI4ZMiGY5OLzkwdSeGV1DTW2+JtJe/98yWyeFhLLM1ovRvVSXdK5sRJvnhfr/C78lqz19UduZnR0c3vyLFuxuZU0UwkZUxuYcnswuAc3/2HA/7qrfrK7Y4cfUsU6edcspl5WaXSL2btPFNNTPP3kRuP34nZteOovhPUX4qxZViCsWz+TIoTzJwe6/IlFXJjLvS5s14kiqAXFjhgIvk14zGXDEP7VsfZ1icXDqjM1sHxKR7vRBQkRzzHR5axvXACXHqO8B5FR/aU1mMTvQx5ORoLxcEA268uuazE8F9kL9rZUdtQ1ADJSwgjhIxwIEsd+HTVpB11VrgdeLYc1+XuZBxKea5b/vmYbV05je+N3rMcWnxabH6LeTTWUY7WHhijhD3sYThDiG3te1za9uKN4WQllkjvNsyOnmwRSiVpAcHC1s+AcD3swVHVOU45ksHdsFGWE8kQpSMIAgCAIAgCAIAgCA7ZKZzWseWkNffCeeE2PwK8yj3B1L08OyOIkF1iWtsXEcATbXhmUPS/wCwd9qKkhDYqWUPPr95pLiOJk1PhYALOu0dtssylyLteprrjhR5lx2FvFJUta8Uk7Y3aPxxkeNi4H4Aqjdpo1vHGs+paqulPnwvBYFULAQ9CAIDOt/600lfSVTL3wFrh7zWu7zfg76LV0cFbTKDM/VS4LYzRoUUgc0OabhwBB5gi4KzJJp4ZfTyso8u2NmsqYXwyeq8WvxB4OHUHNdVWOuakjiyCnHhZxSUsdLThkbe5Ew5cTYEk+JNz5r2UpW2Ze7EYquGF0PXFIHNDmm4cAQeYIuCo2mnhnaeVlFc372O6aATRXE9P95G5uRsM3N+AuOo6lW9HcoT4JbMramvijxLdGO7XrzUSumcAHPsXW0Lg0AutwuRfzW5CChHhRlTk5PLPGujk7Yqdzg9zQSGDE48gXBtz5uAXmUtz1Js6l6eBAEAQBAEAQBAEB9McQQRqMx4hAWzbe9wnpW07WYXNwgyYWDtAW/ed0D7u7rHu62zVWrTcFjnnfp+9yzZfxQUSoq0Vi8ejCminNXTyi4kiGXRr9RyIJaVR105QUZx6Mt6SMZOUX1R6Ni7hMdWzwTSOcyAMcMPdLxILtueFrEGy5t1rVUZxXNnVelTscW9jRtkbIhpWFkDMDSbkXJubAX7xPABZVt07XmTNCuuMFiJ7lESHk2lSGVha17o3jNj2+y7gSNHN5tORUlc+B81ldjiceJcngrWw98vvXUlaGxTtOHEMmPPDX1SdRwPTRW7tH7PiVc0Vq9Tz4J8mXBUC2ZL6WK9slRFG037Nhv/ABOeQR/SPitv7PrcINvqZesmpSSXQvHo+qjJQQE6tBZ5MeQPlZZ+tjw3MuaV5qRYlULJH7cqA2mqXX9SN9+h7Mn8wpqYt2RXvIrZYgyO3AqjJQU5OrQWeTHlo/pAUmtjw3M40ss1IsKqlgwnffZP2aslYBZjvvGfwv4eRxDyX0emt8StSMTUV8E2iBU5CW3dnextNA+F7C/GSAcLD2bcORFx953jfC7LJVb9N4k1JPGPmWKr+CLTRVZpC5xc43JNyepVort5PhAEAQBAEAQBAEB69m7NlqHFkLC9wF8Ite3Ox1XM5xgsyeDqMHJ4RI7y7szUbjiaezuA15sA4loJAGpsb/BR03xtWYndtMq3zINTERJ7t7XdSVEc4uQ02cPeYcnD4adbKK6tWQcWSVWcElI02XaZfVsqqFklQzsxHUBoAGG4czC5xF5RiN2i+WWSzFVw1eHa8c+X77F92Zs461nv++5aqHaMcwOB2Y9ZjgWvbf3mOzb5hUZ1Shv+hbhNS2PUozsIDMfS9swB0NSB6143+Lc2H4Yh5Ba/2bZlOD6GbrYYakVzZe+1ZBGYmSBzbWbjGIs/hJ+huOitWaSqcuJr9SvDU2RWEyvySOcS5xJJ1JNyfElWSA2r0bwluz4b+0Xu8jIbfIXWDrnm5+hr6RfykWdUy0Zrvlt7D/iUIPrOp2N84yZD4WYB5rY01GVXLtn9DMvtw5x8iwejJttnx9XPP9ZH5Kpr/wCs/Qs6P+kWpUi0Zn6Y4xeldxIkHiAWEfC5+K1vsxvEl5fUztclmLM3WoZ5M7ubuy1b2hjTgxBr3i3cB1JGumiiuujUsyJaqpWPCPJtXZM1M4NmYWE3sCRmAdfBdQsjNZizmcJQeGeFdnAQBAEAQBAEAQHr2TW9hNHNhDjGcQBJAxD1b24Xtlx0XM48UXHudQlwyTPZvDt+SsMbpQ3GwFpc3IOGK47vAi5zGuS4qpjUmo7Hdtrsw2RClIj3bD2cameKBuRe4C/IauPkASuLJqEHJ9DuuHHJRN+oKJkEbYomhrGCwA+p5k6kr5uc5Tk5S3ZtwgorhRxWULJbY25t9VwJa5vVrxm3817CyUNvh0EoKW59UrXgYXnFbR9gC4fvAZB3O2R1y0Hk3F818BHK5M71wdlG9Lrh9kiHEzA+Qjkv9QtH7N/qPyKOt+4vMyRbJmFh/wAAkEdNFhPbVb8TW+7G0Wa4jhcucfBoUHjRzJ9Ik3hPCXVm2UFI2GOOJvqxtDR4NFl8/ObnJyfU2YRUYpI+55msa57iA1oLnE8A0XJ+C8jFyeEJPCyzFaSidWOrax7TgaHuHWWTKNg5kXBy5DmvoJTVXDWt/otzHUXZxTZrGyKYUlLTwm1xgYer3m7z8S8rFsfi2Sl++RqQXhwUSWVcmMp9L1WHTwxD2GFx8ZHafBg+K2vs6OK3LuzL1sszSKCtApEpsDbT6R75IwO0LCxpOYbcgl1uJy4qO2qNq4ZbEldjreUdW29pGpmdM5oa59i4DTEGgEi+gNr24L2uChFRXQ8nPjlxM8C7OAgCAIAgCAIAgOyBgLgHOwgnN1ibDnYZnyRhFm3u3XZRxwu7Vpc9vqgO7zwbucCRZos5uRz6Krp9Q7XJY2LF1KrS5lVVorlj9HtS2OvgL7AEubc8HPjc1vxJA81W1cXKmSRPppKNibNqiqmufJGPWjw3HR4uD8j8FguDUVLubCkm2ux3rg6K7tjfajpyWukL3jVsYx2PInJoPS6t16K2azjHmVrNTXHlnJC//aNNf9DUW/B9MSn/AONn+JEX8dHsyrb67w/4jJCynZLhaDZpHec95z7rSb5AfNXNLp/Ai3JlXUXeLJKKLFuhuAIrT1mEuHeEWRa22d3nQkctPFVtTrs+xV8f9FijSY9qfwLLsrZ3aVD66UEOcMELSLFkI9ojg5+ZtqAbc1Vts4YKqPr5k9cOKTsfp5E8qhZK7vRFJVD7HCcIdYzycGR64Bze7LLlrYEK5p3Gr+bP0XcrXZn/AC4+pJUWxoYoWQMb3GFrgNbuaQ4OdzOIA+ShldOU3J7skjVGMVEj4qoVVZZljFSXu4aOqHtLcI54GF1+rlK4+FTz3l+X6kal4lnLaP5k5PM1jXPeQGtBc4ngALkqtGLk8Ink0lln5/3g2mamolnPtuuByaMmjyaAvpKq/DgoroYdk+OTkR6kOC0bmbstre0vIAWNPdId6zhaN1xkRi4a5aKtqL/CxyyWKKVZnmV2riax7mteHgG2IAtB6gOz+KsJ5XMgawzpXp4EAQBAEAQBAEByCgO2SpkeCHOe4E4zck945Fxvx6rxJI9bbOlenhyCgLdu1vpJHVNlqHFzXMbFIbZlrScLzb1nNv4kX4qpfpYzr4Y+ZZq1DjPil5Fl9JW9JZGyCnePvm43Paf1Z9UNI96x8h1VTQ6bm5zW3Isau/koxe5St2d231jagsviiYC0e88nJnm1rvOyv3Xqpxz1KlVLsTx0I3Zey5aiZsMbSXk2scsNtS7kBxUk7Iwi5S2I4Qc5cKNp3X3Whom90B0pHelIzPMN91vT4rC1Gqlc+y7GvTp41r3k65oORVZPBO+ZyvD0IDpnmZExz3uaxjcySbAcySu4qU3hc2cNqKyyiVm8c+0ZTS0GJkX6ycgghp4j3Qc7D1j0zWlDT16ePiW832KUrp3S4K9u5dNjbLjpoWQxDut4nVxOrj1JWfbbK2TlIuV1qEcIzv0k72CS9JA67AfvXjRxHsA8gdeZ+epotLw/zJ79ChqtRxexHYzxaJRCA7Y53tFmuc0Eh2RIuW3wnxGdjwzXjSe56m0fEjy4lxJJJuSeJOpXp4fKAIAgCAIAgCAIAgJvd/bMcDJmyQsk7RuEEgHBqb5+t3gw4ehUVlbm008Y+ZLXNRTTWckKSpSI4QBAcoDdtzNjikpWMOT3DHIf3nAZeQsPJfP6q3xbeXkjZ09fhwI/cOma/wC0V2FoNRK/DYWtG11h5k3vzsFLrJOPDV2Rxpop5s7stqoFsIAgIneHeCGjZjldmfVYPWeeg4DqclPRp53PEfiQ23RrXMzuhlm23UlkrzHDGC/AzMNFwAM9Xm/rHrlwWpJQ0leYrLZQi5ameG8I0/ZezYqeMRQsDWjlqTzJ4nqsiy2VkuKTNGFcYLETO9/d9y4upqV1mjKSQe1za0+7zPHw11NJo+H2579ihqdTn2YGdLSKIQBATm2NtRzQQxNhYx0Ys54De/cXOnqjEXGw1vw0UUK3GTbec/IlnNSiklsQalIggCAIAgCAIAgCAIAgJbd7YT6uVsYcGNcS0SOBw4g3FgBGriBpdRW2quLkySutzlg8FbSPhkdFI0tewlrgeY/LqpIyUllHEouLwzoXp4ezY5b28OO2HtGYr6YcYvfyXM88LwdQxxLJve3JC2nncNRG8/0FfOUrNkV70bdnKDZH7jxBtBTAe5fzc4uPzKk1bzdI4039JE6qxOEBVd8d8o6MGNlnzkZN4Mvo59v7dT0V3S6N2+1LlH8yrfqVXyW5j20K+Sd5kle57zqT9ANAOgW3GEYLhisIypScnlmheh2L/qnf6bf7z/4Wb9pv7q8y7oV95+R7fSXvQYW/ZYXWkeLyOHsMPsjk53yHio9DpuJ+JLboSau/C4ImTrYMwIDsp4HSOaxgLnOIDQNSSbALxtJZZ6k3yRKbxbvyUjywuDw0MxOaDZjntvgceDsiRzFioqblYsoktqcHgh1MRBAEAQBAEAQBAEAQBAEBbNy9ssAdRVDi2GUgseDYwzC2GQHhmBnwIHC6qaiqWfEhuvmuxZosX3JbP5MsW8+w3VocCA2up295oyFRF7MjP+ZG7TwVem1Vf9H8n2ZNbW7P+y+a7ozN7SCQQQRkQcrEcLLTKB8oDUt0N7W1MBo6hwEpYY2POkgLSACff+visrUaVwmrYbZz5GhTqFKPBLcsO4EpdQQA6sxMI5Fkjhb4WVXWrFzLOleakWFVCwUnfvfQUwMEBBnPrO1EQP1f04cVo6TR8ftz2/MpanU8Psx3/IyOSQuJc4kkm5JNySdSTxK2djLPlAX30Y7VbAytc85MjbJbngxCw6kuaPNUNdU7HBLvgu6SxQUmyl7QrHzSPlkN3PJcfPgOg0V2MVGKiipKTk8s8y6OTkBAaPupsJ1G1krmB1bMCIInfqmkZyv90AHPplqVm6i5Wtxz7C3ff3IvU1uCzj2nsvqRW+212sb9hhfjAdjqJeM01879AeHQDgptNW2/Fksdl2RHfYkvDj6vuymK4VQgCAIAgCAIAgCAIAgCAIC97r7xNmbHT1Ehjmj/AOmqeLTp2b7+s06WORHWxVG+lxbnBZT3X1Rbqt4sRk8NbMk94N3hWuILWQVzRdzf1dQ0e3G7j9Roeaiqu8Fd4fOPuZJZV4j7S+T8jOK2jkhe6OVjmPbkWuFj/uOq0oyUllFGUXF4Z0L08NQ9Ee07tmp3HvA9q251DrNf8w34rK+0q9pryNHRT3j6kzv9vR9jiwRkdvIO7xwN0LyOfAdfBQaPTeLLilsiXU38Cwt2Yw95cSSSSTck5kk6knitwyT5QBAfbJCA4AkBwseoxA2Pm0HyQZPhAdtLTvkc1kbXOc42DQLknwXjaSyz1Jt4Rom727baNzDI1s9a4Yo4AbtiH7SR3ADn8LnNZ117tTxyh1ff3IvVUqt8+cu3bzPPvRvH9n7SKGTtKqTKeoGQYB+pi90DTLTPjp1RRx4lJYitl9Wc228GUnlvd/RGfLQKQQBAEAQBAEAQBAEAQBAEAQBAW3YO9gDG09a10sIN2PBIkhPBzHa5eNx4ZKpbp3njr5P5PzLFd3LhnzXzRcKuKOphBnaKyn9ipiH30Q5SRjM242Hi1U4t1yxH2X2ez8mW5JTj7XtLut15lSr9xXub2tFIypi/dID29C08emvRW46xJ8Ni4X8itLTNrMHlENsatloaqORzHtcw95jgWksOTm2NuGl+NlPZCN1bj3Ia5OuaZ1bxbUNVUSzEmznHCDwYMmj4W87r2qtVwUUeWTc5ORGqQ4CAIDsggc8hrGuc46BoLifILxtJZZ6k3sWnZ24suHtat7KWIamQjEegbfI+OfQqrPWRzw1rifuLEdNLGZ8kW7ZtPHTxE0zRTQ279ZUCz3j/ALcbs8+FwByaVTnKU5Ynzf4Vt6sswSgsw5L8T+iKrtve5rWugocbWu/STvJMsx5lxzA+fhordWmbalb6LoivZescMPj1ZTlcKoQBAEAQBAEAQBAEAQBAEAQBAEAQHt2XtWamfjhkcx3GxyPQg5OHiuJ1xmsSWTuE5QeYsttHvnBK7FVQvjl/zFM7s3eLm+153HRVJaWcfuPK7PmWI6iL++sPuizQbQFQA1lRQVjf2dQ3sZPiAQT+AKq4cHNxlHy5osKXHs1Lz5M8lVu1Tuzk2ZUxnnBI2RviAHA2/Cu43z6WJ+awcumL3g/TmRrt06DntVn8UDz9I1J/E3f4/H9SPwav8vh+hw3dOg97ajv4ad4+safxN3+Px/UeDV/l8P0JKl3apgfu9m1kpGhme2JunEF17fhUctRPrZFeXMkVMOkG/PkeyWs+ztLXTbPoW+5C3tpD8gL/AISuFDxNlKfnyR05cHVR8ubK3X7408bsVPE+olGk9UcVjzZHo3yw+CtR005LEnhdl/sglfBPMVl92VPa+2Z6p2OeRzzwGgb4NGQVquqFaxFFadkpvMmR6kOAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCA9tNtaePKOadg5Nkc36FcyhCW6TOlOS2ZIx75VwyFTL52d8yFC9LS/7USLUWr+5nL9868/8A6ZPLCPmAn8LT+FB6i1/3EdU7YqJMpJ53g8HSOI+BKljXCOyRw5ye7PCuzgIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgOUAsgFkAsgFkAsgFkAsgFkAsgFkAsgFkAsgFkAsgFkAsgFkAsgFkAsgFkAsgFkAsgFkAsgOEAQBAEAQBAEAQBAEAQBAEAQBAEAQBAEAQBAEAQBAEAQBAEB//2Q=="
#avatar: "images/jonathan_doe.jpg"
#avatar:


# All the social media and other sites that we want to link to. The 'show' flag determines if the link is shown.
# The order of this list controls the order of the links on the page. Feel free to add.
links:
  - xing:
      name: Xing
      show: false
      href: https://www.xing.com/profile/YOUR_XING_USERNAME/
      icon: fab fa-xing
  - linkedin:
      name: LinkedIn
      show: false
      href: https://linkedin.com/in/YOUR_LINKEDIN_USERNAME/
      icon: fab fa-linkedin
  - googleplus:
      name: Google+
      show: false
      href: https://plus.google.com/+YOUR_GOOGLEPLUS_USERNAME
      icon: fab fa-google-plus
  - twitter:
      name: Twitter
      show: false
      href: https://twitter.com/YOUR_TWITTER_USERNAME
      icon: fab fa-twitter
  - weibo:
      name: 微博
      show: false
      href: https://weibo.com/YOUR_WEIBO_USERNAME
      icon: fab fa-weibo
  - vine:
      name: Vine
      show: false
      href: https://vine.co/YOUR_VINE_USERNAME
      icon: fab fa-vine
  - facebook:
      name: Facebook
      show: true
      href: https://www.facebook.com/roberto.alcantara.94214?locale=es_LA
      icon: fab fa-facebook
  - vkontakte:
      name: ВКонтакте
      show: false
      href: https://vk.com/YOUR_VK_USERNAME
      icon: fab fa-vk
  - instagram:
      name: Instagram
      show: true
      href: https://www.instagram.com/alcantara3929/
      icon: fab fa-instagram
  - flickr:
      name: Flickr
      show: false
      href: https://flickr.com/photos/YOUR_FLICKR_USERNAME
      icon: fab fa-flickr
  - steam:
      name: Steam
      show: false
      href: http://steamcommunity.com/id/YOUR_STEAM_CUSTOM_ID
      icon: fab fa-steam
  - soundcloud:
      name: Soundcloud
      show: false
      href: https://soundcloud.com/YOUR_SOUNDCLOUD_USERNAME
      icon: fab fa-soundcloud
  - lastfm:
      name: Last.fm
      show: false
      href: http://www.last.fm/user/YOUR_LASTFM_USERNAME
      icon: fab fa-lastfm
  - github:
      name: GitHub
      show: true
      href: https://github.com/Roberto1219
      icon: fab fa-github
  - codepen:
      name: CodePen
      show: false
      href: https://codepen.io/YOUR_CODEPEN_USERNAME
      icon: fab fa-codepen
  - stackoverflow:
      name: Stack Overflow
      show: false
      href: https://stackoverflow.com/users/YOUR_SO_USERNAME/
      icon: fab fa-stack-overflow
  - reddit:
      name: Reddit
      show: false
      href: https://reddit.com/user/YOUR_REDDIT_USERNAME
      icon: fab fa-reddit
  - medium:
      name: Medium
      show: false
      href: https://medium.com/@YOUR_MEDIUM_USERNAME
      icon: fab fa-medium
  - tumblr:
      name: Tumblr
      show: false
      href: https://YOUR_TUMBLR_USERNAME.tumblr.com/
      icon: fab fa-tumblr
  - blog:
      name: Blog
      show: false
      href: http://host.domain/your_blog
      icon: fas fa-book-open
  - email:
      name: Email
      show: false
      href: mailto:jonathan.doe@host.domain
      icon: fas fa-envelope
  - publickey:
      name: PGP Key
      show: false
      href: https://pastebin.com/raw/YOUR_PUBLIC_KEY
      icon: fas fa-key


# Extra HTML which will be displayed below the links. Keep it short. Leave empty to disable.
#extra_html:
extra_html: >
    Any (multiline) text containing simple HTML,
    such as links or ... lorem ipsum.

#EOF
